// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from 'vitest'
import { act, cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import App from './App'

afterEach(() => {
  cleanup()
  vi.useRealTimers()
  vi.unstubAllGlobals()
})

function next(count: number) {
  for (let step = 0; step < count; step++) {
    fireEvent.click(screen.getByRole('button', { name: 'Siguiente' }))
  }
}

function codeLines(panel: HTMLElement) {
  return within(panel).getAllByRole('listitem').map((line) => line.textContent)
}

describe('feed y Modo Rayos X', () => {
  it('mantiene el feed y ofrece el mapa con iconos desde el inicio y navegación en el header', async () => {
    const user = userEvent.setup()
    render(<App />)
    expect(document.querySelectorAll('.feed__stream > article')).toHaveLength(8)
    expect(document.querySelectorAll('.post__media svg')).toHaveLength(8)
    await user.click(screen.getByRole('button', { name: 'Ver mapa completo' }))
    expect(screen.getByRole('heading', { name: 'Así se conecta todo.' })).toBeTruthy()
    expect(document.activeElement).toBe(screen.getByRole('heading', { name: 'Así se conecta todo.' }))
    expect(document.querySelectorAll('.architecture__icon svg, .architecture__api-icon svg')).toHaveLength(6)
    const branches = document.querySelector('.architecture__branches')
    expect(branches?.previousElementSibling?.textContent).toContain('Backend')
    expect(branches?.querySelectorAll(':scope > .architecture__node')).toHaveLength(2)
    expect(branches?.querySelectorAll(':scope > .architecture__branch-arrow')).toHaveLength(2)
    expect(screen.getByText('Algoritmo / IA')).toBeTruthy()
    expect(document.querySelector('.overview__note, .overview__back, .overview__closing button')).toBeNull()
    await user.click(screen.getByRole('button', { name: 'Volver al feed' }))
    expect(document.querySelectorAll('.feed__stream > article')).toHaveLength(8)
  })

  it('deja el diagrama limpio en reposo y avanza solo con el botón manual', () => {
    vi.useFakeTimers()
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Modo Rayos X' }))
    fireEvent.click(screen.getByRole('tab', { name: 'Arquitectura' }))
    expect(screen.getByText('Así funciona')).toBeTruthy()
    const nodes = screen.getByRole('tabpanel', { name: 'Arquitectura' }).querySelectorAll('.xray__diagram > .xray__node')
    expect(nodes).toHaveLength(6)
    expect(nodes[3].classList.contains('xray__node--backend')).toBe(true)
    expect(nodes[4].classList.contains('xray__node--database')).toBe(true)
    expect(nodes[5].classList.contains('xray__node--algorithm')).toBe(true)
    expect(document.querySelector('.xray__note, .xray__explanation')).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: /Dar Me gusta a Los mundos abiertos/ }))
    expect(screen.getByLabelText('843 Me gusta')).toBeTruthy()
    expect(screen.getByRole('listitem', { current: 'step' }).textContent).toContain('Frontend')
    act(() => vi.advanceTimersByTime(5000))
    expect(screen.getByRole('listitem', { current: 'step' }).textContent).toContain('Frontend')
    next(1)
    expect(screen.getByText('La API envía POST /likes.')).toBeTruthy()

    fireEvent.click(screen.getAllByRole('button', { name: 'Seguir a PixelZone' })[0])
    expect(screen.getAllByRole('button', { name: 'Dejar de seguir a PixelZone' })).toHaveLength(2)
    expect(screen.getByText('Alex siguió a @PixelZone.')).toBeTruthy()
    next(3)
    expect(screen.getByText('Alex | sigue a | PixelZone')).toBeTruthy()
    next(1)
    expect(screen.getByText('El feed ya muestra el nuevo seguimiento.')).toBeTruthy()
    fireEvent.click(screen.getByRole('button', { name: 'Finalizar' }))
    expect(document.querySelector('.xray__explanation')).toBeNull()
    expect(screen.queryByRole('listitem', { current: 'step' })).toBeNull()
    expect(document.activeElement).toBe(screen.getByRole('heading', { name: 'Así funciona' }))
  })

  it('reordena recomendaciones, explica el algoritmo y permite reiniciar desde el header', () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: /Mejorar mis recomendaciones/ }))
    expect(screen.getByRole('status').textContent).toContain('da Me gusta o sigue')
    fireEvent.click(screen.getByRole('button', { name: /Dar Me gusta a Los mundos abiertos/ }))
    fireEvent.click(screen.getAllByRole('button', { name: 'Seguir a PixelZone' })[0])
    fireEvent.click(screen.getByRole('button', { name: 'Modo Rayos X' }))
    fireEvent.click(screen.getByRole('tab', { name: 'Arquitectura' }))
    fireEvent.click(screen.getByRole('button', { name: /Mejorar mis recomendaciones/ }))
    const cards = document.querySelectorAll('.feed__stream > article')
    expect(within(cards[1] as HTMLElement).getByText(/Un universo entero hecho de píxeles/)).toBeTruthy()
    next(4)
    expect(within(screen.getByRole('tabpanel', { name: 'Arquitectura' })).getByText(/Videojuegos \+3/)).toBeTruthy()
    fireEvent.click(screen.getByRole('button', { name: 'Ver mapa completo' }))
    expect(screen.getByRole('heading', { name: 'Así se conecta todo.' })).toBeTruthy()
    fireEvent.click(screen.getByRole('button', { name: 'Reiniciar demo' }))
    expect(screen.getByLabelText('842 Me gusta')).toBeTruthy()
    expect(screen.queryByText('Así funciona')).toBeNull()
  })

  it('muestra la eliminación contextual y permite salir de Rayos X a mitad del recorrido', () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Modo Rayos X' }))
    fireEvent.click(screen.getByRole('tab', { name: 'Arquitectura' }))
    fireEvent.click(screen.getByRole('button', { name: /Dar Me gusta a Los mundos abiertos/ }))
    fireEvent.click(screen.getByRole('button', { name: /Quitar Me gusta de Los mundos abiertos/ }))
    expect(screen.getByLabelText('842 Me gusta')).toBeTruthy()
    next(3)
    expect(screen.getByText('Se eliminó: Alex | Videojuegos | ♥')).toBeTruthy()
    fireEvent.click(screen.getAllByRole('button', { name: 'Seguir a PixelZone' })[0])
    fireEvent.click(screen.getAllByRole('button', { name: 'Dejar de seguir a PixelZone' })[0])
    next(3)
    expect(screen.getByText('Se eliminó: Alex | sigue a | PixelZone')).toBeTruthy()
    fireEvent.click(screen.getByRole('button', { name: 'Cerrar Rayos X' }))
    expect(screen.queryByText('Así funciona')).toBeNull()
    expect(screen.getAllByRole('button', { name: 'Seguir a PixelZone' })).toHaveLength(2)
  })

  it('permite navegar con teclado también con movimiento reducido', async () => {
    vi.stubGlobal('matchMedia', vi.fn(() => ({ matches: true })))
    const user = userEvent.setup()
    render(<App />)
    await user.tab()
    await user.tab()
    await user.tab()
    expect(document.activeElement).toBe(screen.getByRole('button', { name: 'Modo Rayos X' }))
    await user.keyboard('{Enter}')
    const like = screen.getByRole('button', { name: /Dar Me gusta a Los mundos abiertos/ })
    like.focus()
    await user.keyboard('{Enter}')
    const programming = screen.getByRole('tabpanel', { name: 'Programación' })
    expect(codeLines(programming)).toContain('contador += 1')
    const programmingTab = screen.getByRole('tab', { name: 'Programación' })
    programmingTab.focus()
    await user.keyboard('{ArrowRight}')
    expect(screen.getByText('Alex dio Me gusta a «Los mundos abiertos que no querrás abandonar».')).toBeTruthy()
    const advance = screen.getByRole('button', { name: 'Siguiente' })
    advance.focus()
    await user.keyboard('{Enter}')
    expect(screen.getByText('La API envía POST /likes.')).toBeTruthy()
    const map = screen.getByRole('button', { name: 'Ver mapa completo' })
    map.focus()
    await user.keyboard('{Enter}')
    expect(document.activeElement).toBe(screen.getByRole('heading', { name: 'Así se conecta todo.' }))
  })

  it('explica Me gusta y su reverso, conservando el recorrido al alternar pestañas', async () => {
    vi.stubGlobal('matchMedia', vi.fn(() => ({ matches: true })))
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: 'Modo Rayos X' }))
    const architectureTab = screen.getByRole('tab', { name: 'Arquitectura' })
    const programmingTab = screen.getByRole('tab', { name: 'Programación' })
    expect(screen.getAllByRole('tab').map((tab) => tab.textContent)).toEqual(['Programación', 'Arquitectura'])
    expect(programmingTab.getAttribute('aria-selected')).toBe('true')
    const program = screen.getByRole('tabpanel', { name: 'Programación' })
    expect(program.textContent).toBe('Realiza una acción para continuar.')
    expect(program.tabIndex).toBe(-1)
    expect(within(program).queryByRole('region')).toBeNull()
    programmingTab.focus()
    await user.keyboard('{ArrowRight}')
    expect(document.activeElement).toBe(architectureTab)
    await user.keyboard('{ArrowLeft}')
    expect(document.activeElement).toBe(programmingTab)

    await user.click(screen.getByRole('button', { name: /Dar Me gusta a Los mundos abiertos/ }))
    expect(screen.getByLabelText('843 Me gusta')).toBeTruthy()
    expect(program.tabIndex).toBe(0)
    expect(within(program).getByText('reglas.pseudo')).toBeTruthy()
    expect(within(program).getByText('Solo lectura')).toBeTruthy()
    expect(codeLines(program)).toContain('# Datos')
    expect(codeLines(program)).toContain('# Condición')
    expect(codeLines(program)).toContain('# Instrucciones')
    expect(codeLines(program)).toContain('# Prueba')
    expect(codeLines(program)).toContain('contador = 842')
    expect(codeLines(program)).toContain('me_gusta = False')
    expect(codeLines(program)).toContain('if not me_gusta:')
    expect(codeLines(program)).toContain('me_gusta = True')
    expect(codeLines(program)).toContain('contador += 1')
    expect(codeLines(program)).toContain('comprobar(contador == 843)')
    expect(codeLines(program).some((line) => line?.includes('Si vuelves a pulsar'))).toBe(true)
    await user.click(architectureTab)
    expect(screen.getByRole('listitem', { current: 'step' }).textContent).toContain('Frontend')
    next(1)
    expect(screen.getByRole('listitem', { current: 'step' }).textContent).toContain('API')
    architectureTab.focus()
    await user.keyboard('{Home}')
    expect(document.activeElement).toBe(programmingTab)
    await user.keyboard('{End}')
    expect(document.activeElement).toBe(architectureTab)
    expect(screen.getByRole('listitem', { current: 'step' }).textContent).toContain('API')
    next(3)
    fireEvent.click(screen.getByRole('button', { name: 'Finalizar' }))
    expect(document.querySelector('.xray__explanation')).toBeNull()
    await user.click(programmingTab)
    expect(codeLines(program)).toContain('contador += 1')

    await user.click(screen.getByRole('button', { name: /Quitar Me gusta de Los mundos abiertos/ }))
    expect(screen.getByLabelText('842 Me gusta')).toBeTruthy()
    expect(codeLines(program)).toContain('contador = 843')
    expect(codeLines(program)).toContain('if me_gusta:')
    expect(codeLines(program)).toContain('me_gusta = False')
    expect(codeLines(program)).toContain('contador -= 1')
    expect(codeLines(program)).toContain('comprobar(contador == 842)')
    expect(codeLines(program)).not.toContain('contador += 1')
    await user.click(screen.getByRole('button', { name: 'Cerrar Rayos X' }))
    await user.click(screen.getByRole('button', { name: 'Modo Rayos X' }))
    expect(screen.getByRole('tab', { name: 'Programación' }).getAttribute('aria-selected')).toBe('true')
    expect(screen.getByRole('tabpanel', { name: 'Programación' }).textContent).toBe('Realiza una acción para continuar.')
  })

  it('explica Seguir para todas las publicaciones y las recomendaciones con y sin señales', () => {
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Modo Rayos X' }))
    const program = screen.getByRole('tabpanel', { name: 'Programación' })
    fireEvent.click(screen.getByRole('button', { name: /Mejorar mis recomendaciones/ }))
    expect(codeLines(program)).toContain('me_gusta = 0')
    expect(codeLines(program)).toContain('autores_seguidos = 0')
    expect(codeLines(program)).toContain('if me_gusta == 0 and autores_seguidos == 0:')
    expect(codeLines(program)).toContain('orden_nuevo = orden_actual')
    fireEvent.click(screen.getByRole('tab', { name: 'Arquitectura' }))
    expect(screen.queryByRole('listitem', { current: 'step' })).toBeNull()

    fireEvent.click(screen.getAllByRole('button', { name: 'Seguir a PixelZone' })[0])
    fireEvent.click(screen.getByRole('tab', { name: 'Programación' }))
    expect(codeLines(program)).toContain('categorias = ["Videojuegos"]')
    expect(codeLines(program)).toContain('publicaciones = 2')
    expect(codeLines(program)).toContain('if not siguiendo:')
    expect(codeLines(program)).toContain('mostrar_en_publicaciones(autor, "Siguiendo")')
    expect(screen.getAllByRole('button', { name: 'Dejar de seguir a PixelZone' })).toHaveLength(2)
    fireEvent.click(screen.getByRole('button', { name: /Dar Me gusta a Los mundos abiertos/ }))
    fireEvent.click(screen.getByRole('button', { name: /Mejorar mis recomendaciones/ }))
    expect(codeLines(program)).toContain('puntos_actuales = {"Videojuegos":3}')
    expect(codeLines(program)).toContain('if me_gusta > 0 or autores_seguidos > 0:')
    expect(codeLines(program).some((line) => line?.includes('+1 por Me gusta; +2 por categoría'))).toBe(true)
    expect(codeLines(program)).toContain('feed = ordenar_por_puntos(puntos, empates="orden_original")')

    fireEvent.click(screen.getByRole('button', { name: /Quitar Me gusta de Los mundos abiertos/ }))
    fireEvent.click(screen.getAllByRole('button', { name: 'Dejar de seguir a PixelZone' })[0])
    expect(codeLines(program)).toContain('if siguiendo:')
    expect(codeLines(program)).toContain('siguiendo = False')
    expect(codeLines(program)).toContain('mostrar_en_publicaciones(autor, "Seguir")')
    fireEvent.click(screen.getByRole('button', { name: /Mejorar mis recomendaciones/ }))
    expect(codeLines(program)).toContain('if me_gusta == 0 and autores_seguidos == 0:')
    fireEvent.click(screen.getByRole('button', { name: 'Reiniciar demo' }))
    expect(screen.queryByRole('tab', { name: 'Programación' })).toBeNull()
    expect(screen.getAllByRole('button', { name: 'Seguir a PixelZone' })).toHaveLength(2)
    fireEvent.click(screen.getByRole('button', { name: 'Modo Rayos X' }))
    expect(screen.getByRole('tab', { name: 'Programación' }).getAttribute('aria-selected')).toBe('true')
    expect(screen.getByRole('tabpanel', { name: 'Programación' }).textContent).toBe('Realiza una acción para continuar.')
  })
})
